---
- name: Store running_config to control node
  hosts: ios
  connection: network_cli
  gather_facts: no

  tasks:
    - name: get active configuration from device
      include_role:
        name: ansible-network.config_manager
        tasks_from: get

    - name: Ensure that running_config directory exists
      file:
        path: "{{ playbook_dir }}/running_config"
        state: directory
        mode: 0777
      run_once: yes

    - name: display the configurations to the terminal window
      debug:
        msg: "{{configuration.split('\n')}}"

    - name: copy running config to control node
      copy:
        content: "{{configuration}}"
        dest: "{{ playbook_dir }}/running_config/{{inventory_hostname}}.cfg"

    - name: Remove non-config lines
      lineinfile:
        path: "{{ playbook_dir }}/running_config/{{inventory_hostname}}.cfg"
        line: "Building configuration..."
        state: absent

    - name: Remove non-config lines - Regular Expression
      lineinfile:
        path: "{{ playbook_dir }}/running_config/{{inventory_hostname}}.cfg"
        regexp: 'Current configuration.*'
        state: absent
